export const EPS = 1e-12;

export const TYPE = {
  REALIZED_PNL: "REALIZED_PNL",
  COMMISSION: "COMMISSION",
  FUNDING_FEE: "FUNDING_FEE",
  REFERRAL_KICKBACK: "REFERRAL_KICKBACK",
  INSURANCE_CLEAR: "INSURANCE_CLEAR",
  LIQUIDATION_FEE: "LIQUIDATION_FEE",
  TRANSFER: "TRANSFER",
  GRIDBOT_TRANSFER: "GRIDBOT_TRANSFER",
  COIN_SWAP_DEPOSIT: "COIN_SWAP_DEPOSIT",
  COIN_SWAP_WITHDRAW: "COIN_SWAP_WITHDRAW",
  AUTO_EXCHANGE: "AUTO_EXCHANGE",
  EVENT_ORDER: "EVENT_ORDER",
  EVENT_PAYOUT: "EVENT_PAYOUT"
} as const;

export const EVENT_PREFIX = "EVENT_";
